# remote_theme: pages-themes/hacker@v0.2.0
remote_theme: intellizone/hacker@latest
google_analytics: G-40VHMPGT8D
google_adsense: pub-9225181492831805
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
